export const ROBOT_INITIAL_VALUE = {
  id: 0,
  name: "",
  width: "",
  length: "",
  height: "",
  sensorType: "",
  imageUrl: "",
};

export const ROBOTS = [
  {
    id: 1,
    name: "TurtleBot2",
    width: "0.35m",
    length: "0.45m",
    height: "0.15m",
    sensorType: "RGB Camera",
    imageUrl: "https://turtlebot2.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
  {
    id: 2,
    name: "TurtleBot3",
    width: "0.14m",
    length: "0.19m",
    height: "0.13m",
    sensorType: "Lidar",
    imageUrl: "https://turtlebot3.jpg",
  },
  {
    id: 3,
    name: "Jackal",
    width: "0.51m",
    length: "0.81m",
    height: "0.38m",
    sensorType: "Lidar",
    imageUrl: "https://jackal.jpg",
  },
];
